name: Django CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.4]

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: your_database_name
          MYSQL_USER: your_username
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }} # Reference the secret

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dentists/requirements.txt
      - name: Run Database Migrations
        run: |
          python Dentists/manage.py migrate
      - name: Check Database Connectivity
        run: |
          python Dentists/manage.py check
      - name: Run Tests
        run: |
          python Dentists/manage.py test
